package com.chirvi.pocketlib.presentation.ui.theme.pink_theme

import androidx.compose.ui.graphics.Color
import com.chirvi.pocketlib.presentation.ui.theme.Colors

val pink_theme_light_primary = Color(0xFFBD0047)
val pink_theme_light_onPrimary = Color(0xFFFFFFFF)
val pink_theme_light_primaryContainer = Color(0xFFFFD9DD)
val pink_theme_light_onPrimaryContainer = Color(0xFF400012)
val pink_theme_light_secondary = Color(0xFF76565A)
val pink_theme_light_onSecondary = Color(0xFFFFFFFF)
val pink_theme_light_secondaryContainer = Color(0xFFFFD9DD)
val pink_theme_light_onSecondaryContainer = Color(0xFF2C1518)
val pink_theme_light_tertiary = Color(0xFF785831)
val pink_theme_light_onTertiary = Color(0xFFFFFFFF)
val pink_theme_light_tertiaryContainer = Color(0xFFFFDDB8)
val pink_theme_light_onTertiaryContainer = Color(0xFF2B1700)
val pink_theme_light_error = Color(0xFFBA1A1A)
val pink_theme_light_errorContainer = Color(0xFFFFDAD6)
val pink_theme_light_onError = Color(0xFFFFFFFF)
val pink_theme_light_onErrorContainer = Color(0xFF410002)
val pink_theme_light_background = Color(0xFFFFFBFF)
val pink_theme_light_onBackground = Color(0xFF201A1B)
val pink_theme_light_surface = Color(0xFFFFFBFF)
val pink_theme_light_onSurface = Color(0xFF201A1B)
val pink_theme_light_surfaceVariant = Color(0xFFF3DDDF)
val pink_theme_light_onSurfaceVariant = Color(0xFF524345)
val pink_theme_light_outline = Color(0xFF847374)
val pink_theme_light_inverseOnSurface = Color(0xFFFBEEEE)
val pink_theme_light_inverseSurface = Color(0xFF362F2F)
val pink_theme_light_inversePrimary = Color(0xFFFFB2BC)
val pink_theme_light_shadow = Color(0xFF000000)
val pink_theme_light_surfaceTint = Color(0xFFBD0047)
val pink_theme_light_outlineVariant = Color(0xFFD7C1C3)
val pink_theme_light_scrim = Color(0xFF000000)

val pink_theme_dark_primary = Color(0xFFFFB2BC)
val pink_theme_dark_onPrimary = Color(0xFF670023)
val pink_theme_dark_primaryContainer = Color(0xFF910034)
val pink_theme_dark_onPrimaryContainer = Color(0xFFFFD9DD)
val pink_theme_dark_secondary = Color(0xFFE5BDC1)
val pink_theme_dark_onSecondary = Color(0xFF43292D)
val pink_theme_dark_secondaryContainer = Color(0xFF5C3F43)
val pink_theme_dark_onSecondaryContainer = Color(0xFFFFD9DD)
val pink_theme_dark_tertiary = Color(0xFFEABF8F)
val pink_theme_dark_onTertiary = Color(0xFF452B07)
val pink_theme_dark_tertiaryContainer = Color(0xFF5E411C)
val pink_theme_dark_onTertiaryContainer = Color(0xFFFFDDB8)
val pink_theme_dark_error = Color(0xFFFFB4AB)
val pink_theme_dark_errorContainer = Color(0xFF93000A)
val pink_theme_dark_onError = Color(0xFF690005)
val pink_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val pink_theme_dark_background = Color(0xFF201A1B)
val pink_theme_dark_onBackground = Color(0xFFECE0E0)
val pink_theme_dark_surface = Color(0xFF201A1B)
val pink_theme_dark_onSurface = Color(0xFFECE0E0)
val pink_theme_dark_surfaceVariant = Color(0xFF524345)
val pink_theme_dark_onSurfaceVariant = Color(0xFFD7C1C3)
val pink_theme_dark_outline = Color(0xFF9F8C8E)
val pink_theme_dark_inverseOnSurface = Color(0xFF201A1B)
val pink_theme_dark_inverseSurface = Color(0xFFECE0E0)
val pink_theme_dark_inversePrimary = Color(0xFFBD0047)
val pink_theme_dark_shadow = Color(0xFF000000)
val pink_theme_dark_surfaceTint = Color(0xFFFFB2BC)
val pink_theme_dark_outlineVariant = Color(0xFF524345)
val pink_theme_dark_scrim = Color(0xFF000000)

val seedPink = Color(0xFFFF2A69)

val LightPinkColors = Colors(
    primary = pink_theme_light_primary,
    onPrimary = pink_theme_light_onPrimary,
    primaryContainer = pink_theme_light_primaryContainer,
    onPrimaryContainer = pink_theme_light_onPrimaryContainer,
    secondary = pink_theme_light_secondary,
    onSecondary = pink_theme_light_onSecondary,
    secondaryContainer = pink_theme_light_secondaryContainer,
    onSecondaryContainer = pink_theme_light_onSecondaryContainer,
    tertiary = pink_theme_light_tertiary,
    onTertiary = pink_theme_light_onTertiary,
    tertiaryContainer = pink_theme_light_tertiaryContainer,
    onTertiaryContainer = pink_theme_light_onTertiaryContainer,
    error = pink_theme_light_error,
    errorContainer = pink_theme_light_errorContainer,
    onError = pink_theme_light_onError,
    onErrorContainer = pink_theme_light_onErrorContainer,
    background = pink_theme_light_background,
    onBackground = pink_theme_light_onBackground,
    surface = pink_theme_light_surface,
    onSurface = pink_theme_light_onSurface,
    surfaceVariant = pink_theme_light_surfaceVariant,
    onSurfaceVariant = pink_theme_light_onSurfaceVariant,
    outline = pink_theme_light_outline,
    inverseOnSurface = pink_theme_light_inverseOnSurface,
    inverseSurface = pink_theme_light_inverseSurface,
    inversePrimary = pink_theme_light_inversePrimary,
    surfaceTint = pink_theme_light_surfaceTint,
    outlineVariant = pink_theme_light_outlineVariant,
    scrim = pink_theme_light_scrim,
)

val DarkPinkColors = Colors(
    primary = pink_theme_dark_primary,
    onPrimary = pink_theme_dark_onPrimary,
    primaryContainer = pink_theme_dark_primaryContainer,
    onPrimaryContainer = pink_theme_dark_onPrimaryContainer,
    secondary = pink_theme_dark_secondary,
    onSecondary = pink_theme_dark_onSecondary,
    secondaryContainer = pink_theme_dark_secondaryContainer,
    onSecondaryContainer = pink_theme_dark_onSecondaryContainer,
    tertiary = pink_theme_dark_tertiary,
    onTertiary = pink_theme_dark_onTertiary,
    tertiaryContainer = pink_theme_dark_tertiaryContainer,
    onTertiaryContainer = pink_theme_dark_onTertiaryContainer,
    error = pink_theme_dark_error,
    errorContainer = pink_theme_dark_errorContainer,
    onError = pink_theme_dark_onError,
    onErrorContainer = pink_theme_dark_onErrorContainer,
    background = pink_theme_dark_background,
    onBackground = pink_theme_dark_onBackground,
    surface = pink_theme_dark_surface,
    onSurface = pink_theme_dark_onSurface,
    surfaceVariant = pink_theme_dark_surfaceVariant,
    onSurfaceVariant = pink_theme_dark_onSurfaceVariant,
    outline = pink_theme_dark_outline,
    inverseOnSurface = pink_theme_dark_inverseOnSurface,
    inverseSurface = pink_theme_dark_inverseSurface,
    inversePrimary = pink_theme_dark_inversePrimary,
    surfaceTint = pink_theme_dark_surfaceTint,
    outlineVariant = pink_theme_dark_outlineVariant,
    scrim = pink_theme_dark_scrim,
)