package com.chirvi.pocketlib.presentation.ui.theme.green_theme

import androidx.compose.ui.graphics.Color
import com.chirvi.pocketlib.presentation.ui.theme.Colors

val green_theme_light_primary = Color(0xFF3A6A00)
val green_theme_light_onPrimary = Color(0xFFFFFFFF)
val green_theme_light_primaryContainer = Color(0xFFABF762)
val green_theme_light_onPrimaryContainer = Color(0xFF0D2000)
val green_theme_light_secondary = Color(0xFF57624A)
val green_theme_light_onSecondary = Color(0xFFFFFFFF)
val green_theme_light_secondaryContainer = Color(0xFFDBE7C9)
val green_theme_light_onSecondaryContainer = Color(0xFF151E0C)
val green_theme_light_tertiary = Color(0xFF386664)
val green_theme_light_onTertiary = Color(0xFFFFFFFF)
val green_theme_light_tertiaryContainer = Color(0xFFBBECE9)
val green_theme_light_onTertiaryContainer = Color(0xFF00201F)
val green_theme_light_error = Color(0xFFBA1A1A)
val green_theme_light_errorContainer = Color(0xFFFFDAD6)
val green_theme_light_onError = Color(0xFFFFFFFF)
val green_theme_light_onErrorContainer = Color(0xFF410002)
val green_theme_light_background = Color(0xFFFDFCF5)
val green_theme_light_onBackground = Color(0xFF1B1C18)
val green_theme_light_surface = Color(0xFFFDFCF5)
val green_theme_light_onSurface = Color(0xFF1B1C18)
val green_theme_light_surfaceVariant = Color(0xFFE0E4D6)
val green_theme_light_onSurfaceVariant = Color(0xFF44483E)
val green_theme_light_outline = Color(0xFF74796D)
val green_theme_light_inverseOnSurface = Color(0xFFF2F1EA)
val green_theme_light_inverseSurface = Color(0xFF2F312C)
val green_theme_light_inversePrimary = Color(0xFF90DA48)
val green_theme_light_shadow = Color(0xFF000000)
val green_theme_light_surfaceTint = Color(0xFF3A6A00)
val green_theme_light_outlineVariant = Color(0xFFC4C8BA)
val green_theme_light_scrim = Color(0xFF000000)

val green_theme_dark_primary = Color(0xFF90DA48)
val green_theme_dark_onPrimary = Color(0xFF1B3700)
val green_theme_dark_primaryContainer = Color(0xFF2A5000)
val green_theme_dark_onPrimaryContainer = Color(0xFFABF762)
val green_theme_dark_secondary = Color(0xFFBFCBAE)
val green_theme_dark_onSecondary = Color(0xFF29341F)
val green_theme_dark_secondaryContainer = Color(0xFF3F4A34)
val green_theme_dark_onSecondaryContainer = Color(0xFFDBE7C9)
val green_theme_dark_tertiary = Color(0xFFA0CFCD)
val green_theme_dark_onTertiary = Color(0xFF003736)
val green_theme_dark_tertiaryContainer = Color(0xFF1E4E4C)
val green_theme_dark_onTertiaryContainer = Color(0xFFBBECE9)
val green_theme_dark_error = Color(0xFFFFB4AB)
val green_theme_dark_errorContainer = Color(0xFF93000A)
val green_theme_dark_onError = Color(0xFF690005)
val green_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val green_theme_dark_background = Color(0xFF1B1C18)
val green_theme_dark_onBackground = Color(0xFFE3E3DC)
val green_theme_dark_surface = Color(0xFF1B1C18)
val green_theme_dark_onSurface = Color(0xFFE3E3DC)
val green_theme_dark_surfaceVariant = Color(0xFF44483E)
val green_theme_dark_onSurfaceVariant = Color(0xFFC4C8BA)
val green_theme_dark_outline = Color(0xFF8E9286)
val green_theme_dark_inverseOnSurface = Color(0xFF1B1C18)
val green_theme_dark_inverseSurface = Color(0xFFE3E3DC)
val green_theme_dark_inversePrimary = Color(0xFF3A6A00)
val green_theme_dark_shadow = Color(0xFF000000)
val green_theme_dark_surfaceTint = Color(0xFF90DA48)
val green_theme_dark_outlineVariant = Color(0xFF44483E)
val green_theme_dark_scrim = Color(0xFF000000)


val seedGreen = Color(0xFF579C00)

val DarkGreenTheme = Colors(
    primary = green_theme_dark_primary,
    onPrimary = green_theme_dark_onPrimary,
    primaryContainer = green_theme_dark_primaryContainer,
    onPrimaryContainer = green_theme_dark_onPrimaryContainer,
    secondary = green_theme_dark_secondary,
    onSecondary = green_theme_dark_onSecondary,
    secondaryContainer = green_theme_dark_secondaryContainer,
    onSecondaryContainer = green_theme_dark_onSecondaryContainer,
    tertiary = green_theme_dark_tertiary,
    onTertiary = green_theme_dark_onTertiary,
    tertiaryContainer = green_theme_dark_tertiaryContainer,
    onTertiaryContainer = green_theme_dark_onTertiaryContainer,
    error = green_theme_dark_error,
    errorContainer = green_theme_dark_errorContainer,
    onError = green_theme_dark_onError,
    onErrorContainer = green_theme_dark_onErrorContainer,
    background = green_theme_dark_background,
    onBackground = green_theme_dark_onBackground,
    surface = green_theme_dark_surface,
    onSurface = green_theme_dark_onSurface,
    surfaceVariant = green_theme_dark_surfaceVariant,
    onSurfaceVariant = green_theme_dark_onSurfaceVariant,
    outline = green_theme_dark_outline,
    inverseOnSurface = green_theme_dark_inverseOnSurface,
    inverseSurface = green_theme_dark_inverseSurface,
    inversePrimary = green_theme_dark_inversePrimary,
    surfaceTint = green_theme_dark_surfaceTint,
    outlineVariant = green_theme_dark_outlineVariant,
    scrim = green_theme_dark_scrim
)

val LightGreenTheme = Colors(
    primary = green_theme_light_primary,
    onPrimary = green_theme_light_onPrimary,
    primaryContainer = green_theme_light_primaryContainer,
    onPrimaryContainer = green_theme_light_onPrimaryContainer,
    secondary = green_theme_light_secondary,
    onSecondary = green_theme_light_onSecondary,
    secondaryContainer = green_theme_light_secondaryContainer,
    onSecondaryContainer = green_theme_light_onSecondaryContainer,
    tertiary = green_theme_light_tertiary,
    onTertiary = green_theme_light_onTertiary,
    tertiaryContainer = green_theme_light_tertiaryContainer,
    onTertiaryContainer = green_theme_light_onTertiaryContainer,
    error = green_theme_light_error,
    errorContainer = green_theme_light_errorContainer,
    onError = green_theme_light_onError,
    onErrorContainer = green_theme_light_onErrorContainer,
    background = green_theme_light_background,
    onBackground = green_theme_light_onBackground,
    surface = green_theme_light_surface,
    onSurface = green_theme_light_onSurface,
    surfaceVariant = green_theme_light_surfaceVariant,
    onSurfaceVariant = green_theme_light_onSurfaceVariant,
    outline = green_theme_light_outline,
    inverseOnSurface = green_theme_light_inverseOnSurface,
    inverseSurface = green_theme_light_inverseSurface,
    inversePrimary = green_theme_light_inversePrimary,
    surfaceTint = green_theme_light_surfaceTint,
    outlineVariant = green_theme_light_outlineVariant,
    scrim = green_theme_light_scrim
)