package com.chirvi.pocketlib.presentation.ui.theme.blue_theme

import androidx.compose.ui.graphics.Color
import com.chirvi.pocketlib.presentation.ui.theme.Colors

val blue_theme_light_primary = Color(0xFF00629D)
val blue_theme_light_onPrimary = Color(0xFFFFFFFF)
val blue_theme_light_primaryContainer = Color(0xFFCFE5FF)
val blue_theme_light_onPrimaryContainer = Color(0xFF001D33)
val blue_theme_light_secondary = Color(0xFF526070)
val blue_theme_light_onSecondary = Color(0xFFFFFFFF)
val blue_theme_light_secondaryContainer = Color(0xFFD5E4F7)
val blue_theme_light_onSecondaryContainer = Color(0xFF0E1D2A)
val blue_theme_light_tertiary = Color(0xFF695779)
val blue_theme_light_onTertiary = Color(0xFFFFFFFF)
val blue_theme_light_tertiaryContainer = Color(0xFFF0DBFF)
val blue_theme_light_onTertiaryContainer = Color(0xFF231533)
val blue_theme_light_error = Color(0xFFBA1A1A)
val blue_theme_light_errorContainer = Color(0xFFFFDAD6)
val blue_theme_light_onError = Color(0xFFFFFFFF)
val blue_theme_light_onErrorContainer = Color(0xFF410002)
val blue_theme_light_background = Color(0xFFFCFCFF)
val blue_theme_light_onBackground = Color(0xFF1A1C1E)
val blue_theme_light_surface = Color(0xFFFCFCFF)
val blue_theme_light_onSurface = Color(0xFF1A1C1E)
val blue_theme_light_surfaceVariant = Color(0xFFDEE3EB)
val blue_theme_light_onSurfaceVariant = Color(0xFF42474E)
val blue_theme_light_outline = Color(0xFF72777F)
val blue_theme_light_inverseOnSurface = Color(0xFFF1F0F4)
val blue_theme_light_inverseSurface = Color(0xFF2F3033)
val blue_theme_light_inversePrimary = Color(0xFF99CBFF)
val blue_theme_light_shadow = Color(0xFF000000)
val blue_theme_light_surfaceTint = Color(0xFF00629D)
val blue_theme_light_outlineVariant = Color(0xFFC2C7CF)
val blue_theme_light_scrim = Color(0xFF000000)

val blue_theme_dark_primary = Color(0xFF99CBFF)
val blue_theme_dark_onPrimary = Color(0xFF003354)
val blue_theme_dark_primaryContainer = Color(0xFF004A78)
val blue_theme_dark_onPrimaryContainer = Color(0xFFCFE5FF)
val blue_theme_dark_secondary = Color(0xFFB9C8DA)
val blue_theme_dark_onSecondary = Color(0xFF243240)
val blue_theme_dark_secondaryContainer = Color(0xFF3A4857)
val blue_theme_dark_onSecondaryContainer = Color(0xFFD5E4F7)
val blue_theme_dark_tertiary = Color(0xFFD4BEE6)
val blue_theme_dark_onTertiary = Color(0xFF392A49)
val blue_theme_dark_tertiaryContainer = Color(0xFF504060)
val blue_theme_dark_onTertiaryContainer = Color(0xFFF0DBFF)
val blue_theme_dark_error = Color(0xFFFFB4AB)
val blue_theme_dark_errorContainer = Color(0xFF93000A)
val blue_theme_dark_onError = Color(0xFF690005)
val blue_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val blue_theme_dark_background = Color(0xFF1A1C1E)
val blue_theme_dark_onBackground = Color(0xFFE2E2E5)
val blue_theme_dark_surface = Color(0xFF1A1C1E)
val blue_theme_dark_onSurface = Color(0xFFE2E2E5)
val blue_theme_dark_surfaceVariant = Color(0xFF42474E)
val blue_theme_dark_onSurfaceVariant = Color(0xFFC2C7CF)
val blue_theme_dark_outline = Color(0xFF8C9199)
val blue_theme_dark_inverseOnSurface = Color(0xFF1A1C1E)
val blue_theme_dark_inverseSurface = Color(0xFFE2E2E5)
val blue_theme_dark_inversePrimary = Color(0xFF00629D)
val blue_theme_dark_shadow = Color(0xFF000000)
val blue_theme_dark_surfaceTint = Color(0xFF99CBFF)
val blue_theme_dark_outlineVariant = Color(0xFF42474E)
val blue_theme_dark_scrim = Color(0xFF000000)

val seedBlue = Color(0xFF00639E)

val DarkBlueTheme = Colors(
    primary = blue_theme_dark_primary,
    onPrimary = blue_theme_dark_onPrimary,
    primaryContainer = blue_theme_dark_primaryContainer,
    onPrimaryContainer = blue_theme_dark_onPrimaryContainer,
    secondary = blue_theme_dark_secondary,
    onSecondary = blue_theme_dark_onSecondary,
    secondaryContainer = blue_theme_dark_secondaryContainer,
    onSecondaryContainer = blue_theme_dark_onSecondaryContainer,
    tertiary = blue_theme_dark_tertiary,
    onTertiary = blue_theme_dark_onTertiary,
    tertiaryContainer = blue_theme_dark_tertiaryContainer,
    onTertiaryContainer = blue_theme_dark_onTertiaryContainer,
    error = blue_theme_dark_error,
    errorContainer = blue_theme_dark_errorContainer,
    onError = blue_theme_dark_onError,
    onErrorContainer = blue_theme_dark_onErrorContainer,
    background = blue_theme_dark_background,
    onBackground = blue_theme_dark_onBackground,
    surface = blue_theme_dark_surface,
    onSurface = blue_theme_dark_onSurface,
    surfaceVariant = blue_theme_dark_surfaceVariant,
    onSurfaceVariant = blue_theme_dark_onSurfaceVariant,
    outline = blue_theme_dark_outline,
    inverseOnSurface = blue_theme_dark_inverseOnSurface,
    inverseSurface = blue_theme_dark_inverseSurface,
    inversePrimary = blue_theme_dark_inversePrimary,
    surfaceTint = blue_theme_dark_surfaceTint,
    outlineVariant = blue_theme_dark_outlineVariant,
    scrim = blue_theme_dark_scrim
)

val LightBlueTheme = Colors(
    primary = blue_theme_light_primary,
    onPrimary = blue_theme_light_onPrimary,
    primaryContainer = blue_theme_light_primaryContainer,
    onPrimaryContainer = blue_theme_light_onPrimaryContainer,
    secondary = blue_theme_light_secondary,
    onSecondary = blue_theme_light_onSecondary,
    secondaryContainer = blue_theme_light_secondaryContainer,
    onSecondaryContainer = blue_theme_light_onSecondaryContainer,
    tertiary = blue_theme_light_tertiary,
    onTertiary = blue_theme_light_onTertiary,
    tertiaryContainer = blue_theme_light_tertiaryContainer,
    onTertiaryContainer = blue_theme_light_onTertiaryContainer,
    error = blue_theme_light_error,
    errorContainer = blue_theme_light_errorContainer,
    onError = blue_theme_light_onError,
    onErrorContainer = blue_theme_light_onErrorContainer,
    background = blue_theme_light_background,
    onBackground = blue_theme_light_onBackground,
    surface = blue_theme_light_surface,
    onSurface = blue_theme_light_onSurface,
    surfaceVariant = blue_theme_light_surfaceVariant,
    onSurfaceVariant = blue_theme_light_onSurfaceVariant,
    outline = blue_theme_light_outline,
    inverseOnSurface = blue_theme_light_inverseOnSurface,
    inverseSurface = blue_theme_light_inverseSurface,
    inversePrimary = blue_theme_light_inversePrimary,
    surfaceTint = blue_theme_light_surfaceTint,
    outlineVariant = blue_theme_light_outlineVariant,
    scrim = blue_theme_light_scrim
)